# automatically generated by the FlatBuffers compiler, do not modify

# namespace: loadable

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventListEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventListEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventListEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventListEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventListEntry
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # EventListEntry
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventListEntry
    def Target(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # EventListEntry
    def Val(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EventListEntry
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def EventListEntryStart(builder):
    builder.StartObject(5)

def Start(builder):
    EventListEntryStart(builder)

def EventListEntryAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    EventListEntryAddId(builder, id)

def EventListEntryAddType(builder, type):
    builder.PrependUint8Slot(1, type, 0)

def AddType(builder, type):
    EventListEntryAddType(builder, type)

def EventListEntryAddTarget(builder, target):
    builder.PrependUint16Slot(2, target, 0)

def AddTarget(builder, target):
    EventListEntryAddTarget(builder, target)

def EventListEntryAddVal(builder, val):
    builder.PrependUint32Slot(3, val, 0)

def AddVal(builder, val):
    EventListEntryAddVal(builder, val)

def EventListEntryAddOp(builder, op):
    builder.PrependUint8Slot(4, op, 0)

def AddOp(builder, op):
    EventListEntryAddOp(builder, op)

def EventListEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventListEntryEnd(builder)
