# automatically generated by the FlatBuffers compiler, do not modify

# namespace: loadable

class PixelFormat(object):
    R8 = 0
    R10 = 1
    R12 = 2
    R16 = 3
    R16_I = 4
    R16_F = 5
    A16B16G16R16 = 6
    X16B16G16R16 = 7
    A16B16G16R16_F = 8
    A16Y16U16V16 = 9
    V16U16Y16A16 = 10
    A16Y16U16V16_F = 11
    A8B8G8R8 = 12
    A8R8G8B8 = 13
    B8G8R8A8 = 14
    R8G8B8A8 = 15
    X8B8G8R8 = 16
    X8R8G8B8 = 17
    B8G8R8X8 = 18
    R8G8B8X8 = 19
    A2B10G10R10 = 20
    A2R10G10B10 = 21
    B10G10R10A2 = 22
    R10G10B10A2 = 23
    A2Y10U10V10 = 24
    V10U10Y10A2 = 25
    A8Y8U8V8 = 26
    V8U8Y8A8 = 27
    Y8_U8V8_N444 = 28
    Y8_V8U8_N444 = 29
    Y10_U10V10_N444 = 30
    Y10_V10U10_N444 = 31
    Y12_U12V12_N444 = 32
    Y12_V12U12_N444 = 33
    Y16_U16V16_N444 = 34
    Y16_V16U16_N444 = 35
    FEATURE = 36
    FEATURE_X8 = 37
